### ISSUE TITLE
History

### ISSUE THREAD

**Issue by richp10** [s-gv/femtowiki#1]
Really nice project. The only thing I think it *really* needs in order to be useful is to show diff / history. Without that it is not really a wiki.  With that, it does most of what *most* people need from a wiki.

**Comment by s-gv** [comment]
Thanks! I expect to spend more time on this project in August. But pull requests are always welcome!

**Comment by suntong** [comment]
I think the easiest solution to this problem is

- to use git directly for tracking histories for the `.md` files, which has the show diff / history feature built in. 
- which means separating the  source `.md` files and generated  `.html` files into different folders. 

Comment, @s-gv? 

It should be a very simple straightforward easy fix, and it should be enough, which I'd be glad to send in PR if agreed.

**Comment by s-gv** [comment]
Happy to take a PR on this!
